admin/base/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from settings import ADMIN_BASE

from . import views

base_pattern = '^{}'.format(ADMIN_BASE)

urlpatterns = [
    ### ADMIN ###
    url(
        base_pattern,
        include([
            url(r'^$', views.home, name='home'),
            url(r'^admin/', include(admin.site.urls)),
            url(r'^spam/', include('admin.spam.urls', namespace='spam')),
            url(r'^institutions/', include('admin.institutions.urls', namespace='institutions')),
            url(r'^preprint_providers/', include('admin.preprint_providers.urls', namespace='preprint_providers')),
            url(r'^account/', include('admin.common_auth.urls', namespace='auth')),
            url(r'^password/', include('password_reset.urls')),
            url(r'^nodes/', include('admin.nodes.urls', namespace='nodes')),
            url(r'^preprints/', include('admin.preprints.urls', namespace='preprints')),
            url(r'^subjects/', include('admin.subjects.urls', namespace='subjects')),
            url(r'^users/', include('admin.users.urls', namespace='users')),
            url(r'^meetings/', include('admin.meetings.urls',
                                       namespace='meetings')),
            url(r'^project/', include('admin.pre_reg.urls', namespace='pre_reg')),
            url(r'^metrics/', include('admin.metrics.urls',
                                      namespace='metrics')),
            url(r'^desk/', include('admin.desk.urls',
                                   namespace='desk')),
        ]),
    ),
]

admin.site.site_header = 'OSF-Admin administration'

admin/spam/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.SpamList.as_view(), name='spam'),
    url(
        r'^(?P<spam_id>[a-z0-9]+)/$',
        views.SpamDetail.as_view(),
        name='detail'
    ),
    url(
        r'^(?P<spam_id>[a-z0-9]+)/email/$',
        views.EmailView.as_view(),
        name='email'
    ),
    url(
        r'^user/(?P<user_id>[a-z0-9]+)/$',
        views.UserSpamList.as_view(),
        name='user_spam'
    ),
]

admin/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.UserFormView.as_view(), name='search'),
    url(r'^flagged_spam$', views.UserFlaggedSpamList.as_view(), name='flagged-spam'),
    url(r'^known_spam$', views.UserKnownSpamList.as_view(), name='known-spam'),
    url(r'^known_ham$', views.UserKnownHamList.as_view(), name='known-ham'),
    url(r'^workshop$', views.UserWorkshopFormView.as_view(), name='workshop'),
    url(r'^(?P<guid>[a-z0-9]+)/$', views.UserView.as_view(), name='user'),
    url(r'^search/(?P<name>[\w ]+)/$', views.UserSearchList.as_view(), name='search_list'),
    url(r'^(?P<guid>[a-z0-9]+)/reset-password/$', views.ResetPasswordView.as_view(), name='reset_password'),
    url(r'^(?P<guid>[a-z0-9]+)/disable/$', views.UserDeleteView.as_view(), name='disable'),
    url(r'^(?P<guid>[a-z0-9]+)/disable_spam/$', views.SpamUserDeleteView.as_view(), name='spam_disable'),
    url(r'^(?P<guid>[a-z0-9]+)/enable_ham/$', views.HamUserRestoreView.as_view(), name='ham_enable'),
    url(r'^(?P<guid>[a-z0-9]+)/reactivate/$', views.UserDeleteView.as_view(), name='reactivate'),
    url(r'^(?P<guid>[a-z0-9]+)/get_claim_urls/$', views.GetUserClaimLinks.as_view(), name='get_claim_urls'),
    url(r'^(?P<guid>[a-z0-9]+)/two-factor/disable/$', views.User2FactorDeleteView.as_view(), name='remove2factor'),
    url(r'^(?P<guid>[a-z0-9]+)/get_confirmation/$', views.GetUserConfirmationLink.as_view(), name='get_confirmation'),
    url(r'^(?P<guid>[a-z0-9]+)/get_reset_password/$', views.GetPasswordResetLink.as_view(), name='get_reset_password'),
    url(r'^(?P<guid>[a-z0-9]+)/reindex_elastic_user/$', views.UserReindexElastic.as_view(), name='reindex-elastic-user'),
]

api/base/urls.py
from django.conf import settings as drf_settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

from . import views
from . import settings
from . import versioning

default_version = versioning.decimal_version_to_url_path(settings.REST_FRAMEWORK['DEFAULT_VERSION'])

# Please keep URLs alphabetized for auto-generated documentation
urlpatterns = [
    url('^(?P<version>(v2))/',
        include(
            [
                url(r'^$', views.root, name='root'),
                url(r'^status/', views.status_check, name='status_check'),
                url(r'^addons/', include('api.addons.urls', namespace='addons')),
                url(r'^applications/', include('api.applications.urls', namespace='applications')),
                url(r'^citations/', include('api.citations.urls', namespace='citations')),
                url(r'^collections/', include('api.collections.urls', namespace='collections')),
                url(r'^comments/', include('api.comments.urls', namespace='comments')),
                url(r'^docs/', RedirectView.as_view(pattern_name=views.root), name='redirect-to-root', kwargs={'version': default_version}),
                url(r'^files/', include('api.files.urls', namespace='files')),
                url(r'^guids/', include('api.guids.urls', namespace='guids')),
                url(r'^identifiers/', include('api.identifiers.urls', namespace='identifiers')),
                url(r'^institutions/', include('api.institutions.urls', namespace='institutions')),
                url(r'^licenses/', include('api.licenses.urls', namespace='licenses')),
                url(r'^logs/', include('api.logs.urls', namespace='logs')),
                url(r'^metaschemas/', include('api.metaschemas.urls', namespace='metaschemas')),
                url(r'^nodes/', include('api.nodes.urls', namespace='nodes')),
                url(r'^preprints/', include('api.preprints.urls', namespace='preprints')),
                url(r'^preprint_providers/', include('api.preprint_providers.urls', namespace='preprint_providers')),
                url(r'^registrations/', include('api.registrations.urls', namespace='registrations')),
                url(r'^search/', include('api.search.urls', namespace='search')),
                url(r'^taxonomies/', include('api.taxonomies.urls', namespace='taxonomies')),
                url(r'^test/', include('api.test.urls', namespace='test')),
                url(r'^tokens/', include('api.tokens.urls', namespace='tokens')),
                url(r'^users/', include('api.users.urls', namespace='users')),
                url(r'^view_only_links/', include('api.view_only_links.urls', namespace='view-only-links')),
                url(r'^wikis/', include('api.wikis.urls', namespace='wikis')),
            ],
        )
        ),
    url(r'^$', RedirectView.as_view(pattern_name=views.root), name='redirect-to-root', kwargs={'version': default_version})
]


urlpatterns += static('/static/', document_root=drf_settings.STATIC_ROOT)

handler404 = views.error_404

api/users/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.UserList.as_view(), name=views.UserList.view_name),
    url(r'^(?P<user_id>\w+)/$', views.UserDetail.as_view(), name=views.UserDetail.view_name),
    url(r'^(?P<user_id>\w+)/addons/$', views.UserAddonList.as_view(), name=views.UserAddonList.view_name),
    url(r'^(?P<user_id>\w+)/addons/(?P<provider>\w+)/$', views.UserAddonDetail.as_view(), name=views.UserAddonDetail.view_name),
    url(r'^(?P<user_id>\w+)/addons/(?P<provider>\w+)/accounts/$', views.UserAddonAccountList.as_view(), name=views.UserAddonAccountList.view_name),
    url(r'^(?P<user_id>\w+)/addons/(?P<provider>\w+)/accounts/(?P<account_id>\w+)/$', views.UserAddonAccountDetail.as_view(), name=views.UserAddonAccountDetail.view_name),
    url(r'^(?P<user_id>\w+)/institutions/$', views.UserInstitutions.as_view(), name=views.UserInstitutions.view_name),
    url(r'^(?P<user_id>\w+)/nodes/$', views.UserNodes.as_view(), name=views.UserNodes.view_name),
    url(r'^(?P<user_id>\w+)/preprints/$', views.UserPreprints.as_view(), name=views.UserPreprints.view_name),
    url(r'^(?P<user_id>\w+)/registrations/$', views.UserRegistrations.as_view(), name=views.UserRegistrations.view_name),
    url(r'^(?P<user_id>\w+)/relationships/institutions/$', views.UserInstitutionsRelationship.as_view(), name=views.UserInstitutionsRelationship.view_name),
]

admin/spam/forms.py
from django import forms

from osf.models import SpamStatus


class ConfirmForm(forms.Form):
    confirm = forms.ChoiceField(
        choices=[(SpamStatus.SPAM, 'Spam'), (SpamStatus.HAM, 'Ham')],
        widget=forms.RadioSelect(),
    )

admin/users/forms.py
from django import forms


class EmailResetForm(forms.Form):
    emails = forms.ChoiceField(label='Email')

    def __init__(self, *args, **kwargs):
        choices = kwargs.get('initial', {}).get('emails', [])
        self.base_fields['emails'] = forms.ChoiceField(choices=choices)
        super(EmailResetForm, self).__init__(*args, **kwargs)


class WorkshopForm(forms.Form):
    document = forms.FileField(
        label='Select a file'
    )


class UserSearchForm(forms.Form):
    guid = forms.CharField(label='guid', min_length=5, max_length=5, required=False)  # TODO: Move max to 6 when needed
    name = forms.CharField(label='name', required=False)
    email = forms.EmailField(label='email', required=False)

admin/spam/views.py
from __future__ import unicode_literals

from django.views.generic import FormView, ListView, DetailView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import Http404

from osf.models.comment import Comment
from osf.models.user import OSFUser
from osf.models import SpamStatus

from osf.models.admin_log_entry import (
    update_admin_log,
    CONFIRM_HAM,
    CONFIRM_SPAM,
)
from admin.spam.serializers import serialize_comment
from admin.spam.forms import ConfirmForm
from admin.spam.templatetags.spam_extras import reverse_spam_detail


class EmailView(PermissionRequiredMixin, DetailView):
    template_name = 'spam/email.html'
    context_object_name = 'spam'
    permission_required = 'osf.view_spam'

    def get_object(self, queryset=None):
        spam_id = self.kwargs.get('spam_id')
        try:
            return serialize_comment(Comment.load(spam_id))
        except AttributeError:
            raise Http404('Spam with id {} not found.'.format(spam_id))


class SpamList(PermissionRequiredMixin, ListView):
    """ Allow authorized admin user to see the things people have marked as spam

    Interface with OSF database. No admin models.
    """
    template_name = 'spam/spam_list.html'
    paginate_by = 10
    paginate_orphans = 1
    ordering = '-date_last_reported'
    context_object_name = 'spam'
    permission_required = 'osf.view_spam'
    raise_exception = True

    def get_queryset(self):
        return Comment.objects.filter(
            spam_status=int(self.request.GET.get('status', '1'))
        ).exclude(reports={}).exclude(reports=None)

    def get_context_data(self, **kwargs):
        queryset = kwargs.pop('object_list', self.object_list)
        page_size = self.get_paginate_by(queryset)
        paginator, page, queryset, is_paginated = self.paginate_queryset(
            queryset, page_size)
        kwargs.setdefault('spam', map(serialize_comment, queryset))
        kwargs.setdefault('page', page)
        kwargs.setdefault('status', self.request.GET.get('status', '1'))
        kwargs.setdefault('page_number', page.number)
        return super(SpamList, self).get_context_data(**kwargs)


class UserSpamList(SpamList):
    """ Allow authorized admin user to see the comments a user has had
     marked spam

    Interface with OSF database. No admin models.
    """
    template_name = 'spam/user.html'

    def get_queryset(self):
        user = OSFUser.load(self.kwargs.get('user_id', None))

        return Comment.objects.filter(
            spam_status=int(self.request.GET.get('status', '1')),
            user=user
        ).exclude(reports={}).exclude(reports=None).order_by(self.ordering)

    def get_context_data(self, **kwargs):
        kwargs.setdefault('user_id', self.kwargs.get('user_id', None))
        return super(UserSpamList, self).get_context_data(**kwargs)


class SpamDetail(PermissionRequiredMixin, FormView):
    """ Allow authorized admin user to see details of reported spam.

    Interface with OSF database. Logs action (confirming spam) on admin db.
    """
    form_class = ConfirmForm
    template_name = 'spam/detail.html'
    permission_required = 'osf.view_spam'
    raise_exception = True

    def get_context_data(self, **kwargs):
        spam_id = self.kwargs.get('spam_id')
        kwargs = super(SpamDetail, self).get_context_data(**kwargs)
        try:
            kwargs.setdefault('comment',
                              serialize_comment(Comment.load(spam_id)))
        except AttributeError:
            raise Http404('Spam with id "{}" not found.'.format(spam_id))
        kwargs.setdefault('page_number', self.request.GET.get('page', '1'))
        kwargs.setdefault('status', self.request.GET.get('status', '1'))
        kwargs.update({'SPAM_STATUS': SpamStatus})  # Pass status in to check against
        return kwargs

    def form_valid(self, form):
        spam_id = self.kwargs.get('spam_id')
        item = Comment.load(spam_id)
        try:
            if int(form.cleaned_data.get('confirm')) == SpamStatus.SPAM:
                item.confirm_spam()
                item.is_deleted = True
                log_message = 'Confirmed SPAM: {}'.format(spam_id)
                log_action = CONFIRM_SPAM
            else:
                item.confirm_ham()
                item.is_deleted = False
                log_message = 'Confirmed HAM: {}'.format(spam_id)
                log_action = CONFIRM_HAM
            item.save()
        except AttributeError:
            raise Http404('Spam with id "{}" not found.'.format(spam_id))
        update_admin_log(
            user_id=self.request.user.id,
            object_id=spam_id,
            object_repr='Comment',
            message=log_message,
            action_flag=log_action
        )
        return super(SpamDetail, self).form_valid(form)

    @property
    def success_url(self):
        return reverse_spam_detail(
            self.kwargs.get('spam_id'),
            page=self.request.GET.get('page', '1'),
            status=self.request.GET.get('status', '1')
        )

api_tests/users/views/test_user_exceptions.py
# -*- coding: utf-8 -*-
from nose.tools import *  # flake8: noqa

from tests.base import ApiTestCase
from osf_tests.factories import AuthUserFactory

from api.base.settings.defaults import API_BASE


class TestExceptionFormatting(ApiTestCase):
    def setUp(self):

        super(TestExceptionFormatting, self).setUp()

        self.user = AuthUserFactory(
            fullname='Martin Luther King Jr.',
            given_name='Martin',
            family_name='King',
            suffix='Jr.',
            social=dict(
                github='userOneGithub',
                scholar='userOneScholar',
                personal='http://www.useronepersonalwebsite.com',
                twitter='userOneTwitter',
                linkedIn='userOneLinkedIn',
                impactStory='userOneImpactStory',
                orcid='userOneOrcid',
                researcherId='userOneResearcherId'
            )
        )
        self.url = '/{}users/{}/'.format(API_BASE, self.user._id)

        self.user_two = AuthUserFactory()

    def test_updates_user_with_no_fullname(self):
        res = self.app.put_json_api(self.url, {'data': {'id': self.user._id, 'type': 'users', 'attributes': {}}}, auth=self.user.auth, expect_errors=True)
        errors = res.json['errors']
        assert(isinstance(errors, list))
        assert_equal(res.json['errors'][0]['source'], {'pointer': '/data/attributes/full_name'})
        assert_equal(res.json['errors'][0]['detail'], 'This field is required.')

    def test_updates_user_unauthorized(self):
        res = self.app.put_json_api(self.url, expect_errors=True)
        errors = res.json['errors']
        assert(isinstance(errors, list))
        assert_equal(errors[0], {'detail': "Authentication credentials were not provided."})

    def test_updates_user_forbidden(self):
        res = self.app.put_json_api(self.url, auth=self.user_two.auth, expect_errors=True)
        errors = res.json['errors']
        assert(isinstance(errors, list))
        assert_equal(errors[0], {'detail': 'You do not have permission to perform this action.'})

    def test_user_does_not_exist_formatting(self):
        url = '/{}users/{}/'.format(API_BASE, '12345')
        res = self.app.get(url, auth=self.user.auth, expect_errors=True)
        errors = res.json['errors']
        assert(isinstance(errors, list))
        assert_equal(errors[0], {'detail': 'Not found.'})

    def test_basic_auth_me_wrong_password(self):
        url = '/{}users/{}/'.format(API_BASE, 'me')
        res = self.app.get(url, auth=(self.user.username, 'nottherightone'), expect_errors=True)
        assert_equal(res.status_code, 401)

admin/templates/spam/detail.html
{% extends "base.html" %}
{% load static %}
{% load user_extras %}
{% load spam_extras %}
{% block title %}
    <title>Comment</title>
{% endblock title %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <a href="{% reverse_spam_list page=page_number status=status %}"
               class="btn btn-primary">
                Back to general list
            </a>
            <a href="{% reverse_spam_user comment.author_id page=page_number status=status %}"
               class="btn btn-primary">
                Back to user's list
            </a>
            {%  if perms.osf.mark_spam %}
            <a href="{% url 'spam:email' comment.id %}"
               data-toggle="modal" data-target="#email"
               class="btn btn-default">
                Email
            </a>
            {% endif %}
            <div class="modal" id="email">
                <div class="modal-dialog">
                    <div class="modal-content"></div>
                    {# Data from above link #}
                </div>
            </div>
        </div>

        <br>

        {%  if perms.osf.mark_spam %}
        <div class="row">
        <div class="panel col-md-6">
        <form action="{% reverse_spam_detail comment.id page=page_number status=status %}"
              method="post" class="form-inline">
            {% csrf_token %}
            {% if form.errors %}
                <div class="alert alert-danger">{{ form.errors }}</div>
            {% endif %}
            <label for="{{ form.confirm.id_for_label }}">Confirm:</label>
            <div class="btn-group" data-toggle="buttons">
                {% for choice in form.confirm  %}
                    {{ choice.id }}
                <label class="btn btn-primary">
                    <input type="radio" id="{{ choice.id_for_label }}" autocomplete="off">{{ choice.choice_label }}{{ choice.tag }}
                </label>
                {% endfor %}
            </div>
            <input class="btn btn-danger" type="submit" value="Submit">
        </form>
        </div>
        </div>
        {% endif %}

        {# General info about the comment #}
        <div class="row">
            <div class="col-md-6">
                <h4>
                    <strong>Author:</strong> {{ comment.author.fullname }}
                    <small>
                        (<a href="{{ comment.author_path }}">
                            User's <b>osf</b> profile
                        </a>) (<a href="{{ comment.author_id | reverse_user }}">
                            User's profile
                        </a>)
                    </small>
                </h4>
            </div>
            <div class="col-md-6">
                <h4><strong>Comment ID:</strong> {{ comment.id }}</h4>
            </div>
        </div>

        {# Spam Status #}
        <div class="row">
            <div class="col-md-6">
                <h4>
                    <strong>Status: </strong>
                    {% if comment.spam_status == SPAM_STATUS.UNKNOWN %}
                        <span class="label label-default">Unknown</span>
                    {% elif comment.spam_status == SPAM_STATUS.FLAGGED %}
                        <span class="label label-warning">Flagged</span>
                    {% elif comment.spam_status == SPAM_STATUS.SPAM %}
                        <span class="label label-danger">Spam</span>
                    {% elif comment.spam_status == SPAM_STATUS.HAM %}
                        <span class="label label-success">Ham</span>
                    {% endif %}
                </h4>
            </div>
        </div>

        {# Comment date and content #}
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>
                        <strong>Comment content</strong>
                        created on:
                        {{ comment.date_created }}
                    </h4>
                </div>
                <div class="panel-body">
                    {{ comment.content }}
                </div>
            </div>
        </div>

        <h4><strong>Reports</strong></h4>
        {% for report in comment.reports %}
            <div class="row">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>
                            Type:
                            <strong>
                                {{ report.category }}
                            </strong>
                        </h4>
                    </div>
                    <div class="panel-body">
                        <div class="col-md-6">
                            <strong>Reporter:</strong>
                            {{ report.reporter.fullname }}
                            (<a href="{{ report.reporter.pk | reverse_user }}">
                            User's profile
                            </a>)
                        </div>
                        <div class="col-md-6">
                            <strong>
                                Reason:
                            </strong>
                            {{ report.reason|default:"--Nothing--" }}
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <div>No reports!</div>
        {% endfor %}
    </div>

{% endblock content %}

admin/templates/spam/email.html
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">x</button>
    <h3>Suggested Email message for spammer</h3>
</div>
<div class="modal-body">
    <p>Dear {{ spam.author.fullname }},</p>
    <p>A comment you made on an Open Science Framework (OSF) project
        [<a href="{{ spam.node.absolute_url }}">{{ spam.node.absolute_url }}</a>]
        has been reported as
        {% if spam.category == 'hate' %}
            hate speech
        {% elif  spam.category == 'violence' %}
            violent or harmful behavior
        {% else %}
            spam
        {% endif %}
        Our team reviewed your comment and found it to be in violation
        of the OSF Terms of Service:
        <a href="https://github.com/CenterForOpenScience/centerforopenscience.org/blob/master/TERMS_OF_USE.md">
            https://github.com/CenterForOpenScience/centerforopenscience.org/blob/master/TERMS_OF_USE.md
        </a>.
        As a result, your comment has been removed from the project.
        If you have questions about this action, please contact
        <a href="mailto:support@osf.io">support@osf.io</a>.
    </p>
    <p>Best,</p>
    <p>The OSF Team</p>
</div>
<div class="modal-footer">
    <button type="button" class="btn" data-dismiss="modal" >Close</button>
</div>

admin/templates/spam/spam_list.html
{% extends "base.html" %}
{% load render_bundle from webpack_loader %}
{% load spam_extras %}

{% load static %}
{% block title %}
    <title>List of Spam</title>
{% endblock title %}
{% block content %}
    <h2>List of Spam</h2>
    <div class="btn-group">
    {% if status == '1' %}
        <a href=""
           class="btn btn-primary active disabled">Flagged</a>
    {% else %}
        <a href="{% reverse_spam_list page=page_number status=1 %}"
           class="btn btn-primary">Flagged</a>
    {% endif %}
    {% if status == '2' %}
        <a href=""
           class="btn btn-primary active disabled">Spam</a>
    {% else %}
        <a href="{% reverse_spam_list page=page_number status=2 %}"
           class="btn btn-primary">Spam</a>
    {% endif %}
    {% if status == '4' %}
        <a href=""
           class="btn btn-primary active disabled">Ham</a>
    {% else %}
        <a href="{% reverse_spam_list page=page_number status=4 %}"
           class="btn btn-primary">Ham</a>
    {% endif %}
    </div>
    {% include "util/pagination.html" with items=page status=status %}
    <table class="table table-striped table-hover table-responsive">
    <thead>
        <tr>
            <th><label for="all"></label>
                <input id="all" type="checkbox" disabled>
            </th>
            <th>Author</th>
            <th>Reporter</th>
            <th>Date</th>
            <th>Content</th>
        </tr>
    </thead>
    <tbody>
    {% for comment in spam %}
    <tr>
        <td>
            <label for="{{ comment.id }}"></label>
            <input id="{{ comment.id }}" type="checkbox" disabled>
        </td>
        <td>
            {{ comment.author.fullname }}
        </td>
        <td>
            {% with comment.reports|first as first_report %}
                {{ first_report.reporter.fullname }}
            {% endwith %}
        </td>
        <td>
            {{ comment.date_created|date }}
        </td>
        <td>
            {{ comment.content|truncatechars:30 }}
        </td>
        <td>
            <a href="{% reverse_spam_detail comment.id page=page_number status=status %}"
               class="btn btn-primary">
                Detail
            </a>
        </td>
    </tr>
    {% empty %}
    <tr>
        <td>No more Spam!</td>
    </tr>
    {% endfor %}
    </tbody>
    </table>

{% endblock content %}

admin/templates/spam/user.html
{% extends "base.html" %}
{% load render_bundle from webpack_loader %}
{% load spam_extras %}
{% load user_extras %}

{% load static %}
{% block title %}
    <title>User Spam</title>
{% endblock title %}
{% block content %}
    <h2>User's List of Spam</h2>
    <a href="{{ user_id | reverse_user }}" class="btn btn-primary">
        <i class="fa fa-arrow-left"></i>
        User details
    </a>
    <div class="btn-group">
    {% if status == '1' %}
        <a href="" class="btn btn-primary active disabled">Flagged</a>
    {% else %}
        <a href="{% reverse_spam_user user_id page=page_number status=1 %}"
           class="btn btn-primary">Flagged</a>
    {% endif %}
    {% if status == '2' %}
        <a href="" class="btn btn-primary active disabled">Spam</a>
    {% else %}
        <a href="{% reverse_spam_user user_id page=page_number status=2 %}"
           class="btn btn-primary">Spam</a>
    {% endif %}
    {% if status == '4' %}
        <a href="" class="btn btn-primary active disabled">Ham</a>
    {% else %}
        <a href="{% reverse_spam_user user_id page=page_number status=4 %}"
           class="btn btn-primary">Ham</a>
    {% endif %}
    </div>
    {% include "util/pagination.html" with items=page status=status %}
    <table class="table table-striped table-hover table-responsive">
    <thead>
        <tr>
            <th><label for="all"></label>
                <input id="all" type="checkbox" disabled>
            </th>
            <th>Author</th>
            <th>Reporter</th>
            <th>Date</th>
            <th>Content</th>
        </tr>
    </thead>
    <tbody>
    {% for comment in spam %}
    <tr>
        <td>
            <label for="{{ comment.id }}"></label>
            <input id="{{ comment.id }}" type="checkbox" disabled>
        </td>
        <td>
            {{ comment.author.fullname }}
        </td>
        <td>
            {% with comment.reports|first as first_report %}
                {{ first_report.reporter.fullname }}
            {% endwith %}
        </td>
        <td>
            {{ comment.date_created|date }}
        </td>
        <td>
            {{ comment.content|truncatechars:30 }}
        </td>
        <td>
            <a href="{% reverse_spam_detail comment.id page=page_number status=status %}"
               class="btn btn-primary">
                Detail
            </a>
        </td>
    </tr>
    {% empty %}
    <tr>
        <td>No more Spam!</td>
    </tr>
    {% endfor %}
    </tbody>
    </table>

{% endblock content %}