admin/base/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from settings import ADMIN_BASE

from . import views

base_pattern = '^{}'.format(ADMIN_BASE)

urlpatterns = [
    ### ADMIN ###
    url(
        base_pattern,
        include([
            url(r'^$', views.home, name='home'),
            url(r'^admin/', include(admin.site.urls)),
            url(r'^spam/', include('admin.spam.urls', namespace='spam')),
            url(r'^institutions/', include('admin.institutions.urls', namespace='institutions')),
            url(r'^preprint_providers/', include('admin.preprint_providers.urls', namespace='preprint_providers')),
            url(r'^account/', include('admin.common_auth.urls', namespace='auth')),
            url(r'^password/', include('password_reset.urls')),
            url(r'^nodes/', include('admin.nodes.urls', namespace='nodes')),
            url(r'^preprints/', include('admin.preprints.urls', namespace='preprints')),
            url(r'^subjects/', include('admin.subjects.urls', namespace='subjects')),
            url(r'^users/', include('admin.users.urls', namespace='users')),
            url(r'^meetings/', include('admin.meetings.urls',
                                       namespace='meetings')),
            url(r'^project/', include('admin.pre_reg.urls', namespace='pre_reg')),
            url(r'^metrics/', include('admin.metrics.urls',
                                      namespace='metrics')),
            url(r'^desk/', include('admin.desk.urls',
                                   namespace='desk')),
        ]),
    ),
]

admin.site.site_header = 'OSF-Admin administration'

admin/metrics/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required as login

from . import views

urlpatterns = [
    url(r'^$', login(views.MetricsView.as_view()), name='metrics'),
]

admin/nodes/urls.py
from django.conf.urls import url
from admin.nodes import views


urlpatterns = [
    url(r'^$', views.NodeFormView.as_view(),
        name='search'),
    url(r'^flagged_spam$', views.NodeFlaggedSpamList.as_view(),
        name='flagged-spam'),
    url(r'^known_spam$', views.NodeKnownSpamList.as_view(),
        name='known-spam'),
    url(r'^known_ham$', views.NodeKnownHamList.as_view(),
        name='known-ham'),
    url(r'^(?P<guid>[a-z0-9]+)/$', views.NodeView.as_view(),
        name='node'),
    url(r'^registration_list/$', views.RegistrationListView.as_view(),
        name='registrations'),
    url(r'^(?P<guid>[a-z0-9]+)/remove/$', views.NodeDeleteView.as_view(),
        name='remove'),
    url(r'^(?P<guid>[a-z0-9]+)/restore/$', views.NodeDeleteView.as_view(),
        name='restore'),
    url(r'^(?P<guid>[a-z0-9]+)/confirm_spam/$', views.NodeConfirmSpamView.as_view(),
        name='confirm-spam'),
    url(r'^(?P<guid>[a-z0-9]+)/confirm_ham/$', views.NodeConfirmHamView.as_view(),
        name='confirm-ham'),
    url(r'^(?P<guid>[a-z0-9]+)/reindex_share_node/$', views.NodeReindexShare.as_view(),
        name='reindex-share-node'),
    url(r'^(?P<guid>[a-z0-9]+)/reindex_elastic_node/$', views.NodeReindexElastic.as_view(),
        name='reindex-elastic-node'),
    url(r'^(?P<node_id>[a-z0-9]+)/remove_user/(?P<user_id>[a-z0-9]+)/$',
        views.NodeRemoveContributorView.as_view(), name='remove_user'),
]

admin/pre_reg/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required as login

from admin.pre_reg import views

urlpatterns = [
    url(r'^$', views.DraftListView.as_view(), name='prereg'),
    url(r'^download/$', views.DraftDownloadListView.as_view(), name='download'),
    url(
        r'^drafts/(?P<draft_pk>[0-9a-z]+)/$',
        views.DraftDetailView.as_view(),
        name='view_draft'
    ),
    url(
        r'^drafts/(?P<draft_pk>[0-9a-z]+)/update/$',
        views.DraftFormView.as_view(),
        name='update_draft'
    ),
    url(
        r'^drafts/(?P<draft_pk>[0-9a-z]+)/comment/$',
        views.CommentUpdateView.as_view(),
        name='comment'
    ),
    url(
        r'^(?P<node_id>[a-zA-Z0-9]{5})/files/(?P<provider>.+?)/(?P<file_id>.+)/?',
        login(views.view_file),
        name='view_file'
    )
]

admin/spam/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.SpamList.as_view(), name='spam'),
    url(
        r'^(?P<spam_id>[a-z0-9]+)/$',
        views.SpamDetail.as_view(),
        name='detail'
    ),
    url(
        r'^(?P<spam_id>[a-z0-9]+)/email/$',
        views.EmailView.as_view(),
        name='email'
    ),
    url(
        r'^user/(?P<user_id>[a-z0-9]+)/$',
        views.UserSpamList.as_view(),
        name='user_spam'
    ),
]

api/base/urls.py
from django.conf import settings as drf_settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

from . import views
from . import settings
from . import versioning

default_version = versioning.decimal_version_to_url_path(settings.REST_FRAMEWORK['DEFAULT_VERSION'])

# Please keep URLs alphabetized for auto-generated documentation
urlpatterns = [
    url('^(?P<version>(v2))/',
        include(
            [
                url(r'^$', views.root, name='root'),
                url(r'^status/', views.status_check, name='status_check'),
                url(r'^addons/', include('api.addons.urls', namespace='addons')),
                url(r'^applications/', include('api.applications.urls', namespace='applications')),
                url(r'^citations/', include('api.citations.urls', namespace='citations')),
                url(r'^collections/', include('api.collections.urls', namespace='collections')),
                url(r'^comments/', include('api.comments.urls', namespace='comments')),
                url(r'^docs/', RedirectView.as_view(pattern_name=views.root), name='redirect-to-root', kwargs={'version': default_version}),
                url(r'^files/', include('api.files.urls', namespace='files')),
                url(r'^guids/', include('api.guids.urls', namespace='guids')),
                url(r'^identifiers/', include('api.identifiers.urls', namespace='identifiers')),
                url(r'^institutions/', include('api.institutions.urls', namespace='institutions')),
                url(r'^licenses/', include('api.licenses.urls', namespace='licenses')),
                url(r'^logs/', include('api.logs.urls', namespace='logs')),
                url(r'^metaschemas/', include('api.metaschemas.urls', namespace='metaschemas')),
                url(r'^nodes/', include('api.nodes.urls', namespace='nodes')),
                url(r'^preprints/', include('api.preprints.urls', namespace='preprints')),
                url(r'^preprint_providers/', include('api.preprint_providers.urls', namespace='preprint_providers')),
                url(r'^registrations/', include('api.registrations.urls', namespace='registrations')),
                url(r'^search/', include('api.search.urls', namespace='search')),
                url(r'^taxonomies/', include('api.taxonomies.urls', namespace='taxonomies')),
                url(r'^test/', include('api.test.urls', namespace='test')),
                url(r'^tokens/', include('api.tokens.urls', namespace='tokens')),
                url(r'^users/', include('api.users.urls', namespace='users')),
                url(r'^view_only_links/', include('api.view_only_links.urls', namespace='view-only-links')),
                url(r'^wikis/', include('api.wikis.urls', namespace='wikis')),
            ],
        )
        ),
    url(r'^$', RedirectView.as_view(pattern_name=views.root), name='redirect-to-root', kwargs={'version': default_version})
]


urlpatterns += static('/static/', document_root=drf_settings.STATIC_ROOT)

handler404 = views.error_404

addons/base/testing/views.py
# -*- coding: utf-8 -*-
import httplib as http
import urlparse

import httpretty
import mock
from framework.auth import Auth
from framework.exceptions import HTTPError
from nose.tools import *  # noqa (PEP8 asserts)
from osf_tests.factories import AuthUserFactory, ProjectFactory
from addons.base.testing.base import OAuthAddonTestCaseMixin
from website.util import api_url_for, permissions, web_url_for


class OAuthAddonAuthViewsTestCaseMixin(OAuthAddonTestCaseMixin):

    @property
    def Provider(self):
        raise NotImplementedError()

    def test_oauth_start(self):
        url = api_url_for(
            'oauth_connect',
            service_name=self.ADDON_SHORT_NAME
        )
        res = self.app.get(url, auth=self.user.auth)
        assert_equal(res.status_code, http.FOUND)
        redirect_url = urlparse.urlparse(res.location)
        redirect_params = urlparse.parse_qs(redirect_url.query)
        provider_url = urlparse.urlparse(self.Provider().auth_url)
        provider_params = urlparse.parse_qs(provider_url.query)
        for param, value in redirect_params.items():
            if param == 'state':  # state may change between calls
                continue
            assert_equal(value, provider_params[param])

    def test_oauth_finish(self):
        url = web_url_for(
            'oauth_callback',
            service_name=self.ADDON_SHORT_NAME
        )
        with mock.patch.object(self.Provider, 'auth_callback') as mock_callback:
            mock_callback.return_value = True
            res = self.app.get(url, auth=self.user.auth)
        assert_equal(res.status_code, http.OK)
        name, args, kwargs = mock_callback.mock_calls[0]
        assert_equal(kwargs['user']._id, self.user._id)

    def test_delete_external_account(self):
        url = api_url_for(
            'oauth_disconnect',
            external_account_id=self.external_account._id
        )
        res = self.app.delete(url, auth=self.user.auth)
        assert_equal(res.status_code, http.OK)
        self.user.reload()
        for account in self.user.external_accounts:
            assert_not_equal(account._id, self.external_account._id)
        assert_false(self.user.external_accounts)

    def test_delete_external_account_not_owner(self):
        other_user = AuthUserFactory()
        url = api_url_for(
            'oauth_disconnect',
            external_account_id=self.external_account._id
        )
        res = self.app.delete(url, auth=other_user.auth, expect_errors=True)
        assert_equal(res.status_code, http.FORBIDDEN)

class OAuthAddonConfigViewsTestCaseMixin(OAuthAddonTestCaseMixin):

    @property
    def folder(self):
        raise NotImplementedError("This test suite must expose a 'folder' property.")

    @property
    def Serializer(self):
        raise NotImplementedError()

    @property
    def client(self):
        raise NotImplementedError()

    def test_import_auth(self):
        ea = self.ExternalAccountFactory()
        self.user.external_accounts.append(ea)
        self.user.save()

        node = ProjectFactory(creator=self.user)
        node_settings = node.get_or_add_addon(self.ADDON_SHORT_NAME, auth=Auth(self.user))
        node.save()
        url = node.api_url_for('{0}_import_auth'.format(self.ADDON_SHORT_NAME))
        res = self.app.put_json(url, {
            'external_account_id': ea._id
        }, auth=self.user.auth)
        assert_equal(res.status_code, http.OK)
        assert_in('result', res.json)
        node_settings.reload()
        assert_equal(node_settings.external_account._id, ea._id)

        node.reload()
        last_log = node.logs.latest()
        assert_equal(last_log.action, '{0}_node_authorized'.format(self.ADDON_SHORT_NAME))

    def test_import_auth_invalid_account(self):
        ea = self.ExternalAccountFactory()

        node = ProjectFactory(creator=self.user)
        node.add_addon(self.ADDON_SHORT_NAME, auth=self.auth)
        node.save()
        url = node.api_url_for('{0}_import_auth'.format(self.ADDON_SHORT_NAME))
        res = self.app.put_json(url, {
            'external_account_id': ea._id
        }, auth=self.user.auth, expect_errors=True)
        assert_equal(res.status_code, http.FORBIDDEN)

    def test_import_auth_cant_write_node(self):
        ea = self.ExternalAccountFactory()
        user = AuthUserFactory()
        user.add_addon(self.ADDON_SHORT_NAME, auth=Auth(user))
        user.external_accounts.append(ea)
        user.save()

        node = ProjectFactory(creator=self.user)
        node.add_contributor(user, permissions=[permissions.READ], auth=self.auth, save=True)
        node.add_addon(self.ADDON_SHORT_NAME, auth=self.auth)
        node.save()
        url = node.api_url_for('{0}_import_auth'.format(self.ADDON_SHORT_NAME))
        res = self.app.put_json(url, {
            'external_account_id': ea._id
        }, auth=user.auth, expect_errors=True)
        assert_equal(res.status_code, http.FORBIDDEN)

    def test_set_config(self):
        self.node_settings.set_auth(self.external_account, self.user)
        url = self.project.api_url_for('{0}_set_config'.format(self.ADDON_SHORT_NAME))
        res = self.app.put_json(url, {
            'selected': self.folder
        }, auth=self.user.auth)
        assert_equal(res.status_code, http.OK)
        self.project.reload()
        assert_equal(
            self.project.logs.latest().action,
            '{0}_folder_selected'.format(self.ADDON_SHORT_NAME)
        )
        assert_equal(res.json['result']['folder']['path'], self.folder['path'])

    def test_get_config(self):
        url = self.project.api_url_for('{0}_get_config'.format(self.ADDON_SHORT_NAME))
        with mock.patch.object(type(self.Serializer()), 'credentials_are_valid', return_value=True):
            res = self.app.get(url, auth=self.user.auth)
        assert_equal(res.status_code, http.OK)
        assert_in('result', res.json)
        serialized = self.Serializer().serialize_settings(
            self.node_settings,
            self.user,
            self.client
        )
        assert_equal(serialized, res.json['result'])

    def test_get_config_unauthorized(self):
        url = self.project.api_url_for('{0}_get_config'.format(self.ADDON_SHORT_NAME))
        user = AuthUserFactory()
        self.project.add_contributor(user, permissions=[permissions.READ], auth=self.auth, save=True)
        res = self.app.get(url, auth=user.auth, expect_errors=True)
        assert_equal(res.status_code, http.FORBIDDEN)

    def test_get_config_not_logged_in(self):
        url = self.project.api_url_for('{0}_get_config'.format(self.ADDON_SHORT_NAME))
        res = self.app.get(url, auth=None, expect_errors=True)
        assert_equal(res.status_code, http.FOUND)

    def test_account_list_single(self):
        url = api_url_for('{0}_account_list'.format(self.ADDON_SHORT_NAME))
        res = self.app.get(url, auth=self.user.auth)
        assert_equal(res.status_code, http.OK)
        assert_in('accounts', res.json)
        assert_equal(len(res.json['accounts']), 1)

    def test_account_list_multiple(self):
        ea = self.ExternalAccountFactory()
        self.user.external_accounts.append(ea)
        self.user.save()

        url = api_url_for('{0}_account_list'.format(self.ADDON_SHORT_NAME))
        res = self.app.get(url, auth=self.user.auth)
        assert_equal(res.status_code, http.OK)
        assert_in('accounts', res.json)
        assert_equal(len(res.json['accounts']), 2)

    def test_account_list_not_authorized(self):
        url = api_url_for('{0}_account_list'.format(self.ADDON_SHORT_NAME))
        res = self.app.get(url, auth=None, expect_errors=True)
        assert_equal(res.status_code, http.FOUND)

    def test_folder_list(self):
        # Note: if your addon's folder_list view makes API calls
        # then you will need to implement test_folder_list in your
        # subclass, mock any API calls, and call super.
        self.node_settings.set_auth(self.external_account, self.user)
        self.node_settings.save()
        url = self.project.api_url_for('{0}_folder_list'.format(self.ADDON_SHORT_NAME))
        res = self.app.get(url, auth=self.user.auth)
        assert_equal(res.status_code, http.OK)
        # TODO test result serialization?

    def test_deauthorize_node(self):
        url = self.project.api_url_for('{0}_deauthorize_node'.format(self.ADDON_SHORT_NAME))
        res = self.app.delete(url, auth=self.user.auth)
        assert_equal(res.status_code, http.OK)
        self.node_settings.reload()
        assert_is_none(self.node_settings.external_account)
        assert_false(self.node_settings.has_auth)

        # A log event was saved
        self.project.reload()
        last_log = self.project.logs.latest()
        assert_equal(last_log.action, '{0}_node_deauthorized'.format(self.ADDON_SHORT_NAME))

class OAuthCitationAddonConfigViewsTestCaseMixin(OAuthAddonConfigViewsTestCaseMixin):

    @property
    def citationsProvider(self):
        raise NotImplementedError()

    @property
    def foldersApiUrl(self):
        raise NotImplementedError()

    @property
    def documentsApiUrl(self):
        raise NotImplementedError()

    @property
    def mockResponses(self):
        raise NotImplementedError()

    def setUp(self):
        super(OAuthCitationAddonConfigViewsTestCaseMixin, self).setUp()
        self.mock_verify = mock.patch.object(
            self.client,
            '_verify_client_validity'
        )
        self.mock_verify.start()

    def tearDown(self):
        self.mock_verify.stop()
        super(OAuthCitationAddonConfigViewsTestCaseMixin, self).tearDown()

    def test_set_config(self):
        with mock.patch.object(self.client, '_folder_metadata') as mock_metadata:
            mock_metadata.return_value = self.folder
            url = self.project.api_url_for('{0}_set_config'.format(self.ADDON_SHORT_NAME))
            res = self.app.put_json(url, {

admin/templates/base.html
{% load staticfiles %}
{% load render_bundle from webpack_loader %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    {% block title %}
      <title>OSF Admin | Dashboard</title>
    {% endblock %}

    <!-- Tell the browser to be responsive to screen width -->
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap -->
    <link href="{% static 'vendor/bower_components/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{% static 'vendor/bower_components/admin-lte/dist/css/AdminLTE.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- AdminLTE Skins. -->
    <link href="{% static 'vendor/bower_components/admin-lte/dist/css/skins/skin-blue.min.css' %}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="/static/css/base.css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="{% static 'vendor/bower_components/raven-js/dist/raven.min.js' %}"></script>
    <script src="{% static 'vendor/bower_components/jquery/dist/jquery.js' %}"></script>
    <script src="{% static 'vendor/bower_components/jquery-ui/ui/minified/jquery-ui.min.js' %}"></script>

    {% block top_includes %}

    {% endblock %}
  </head>
  <body class="skin-blue sidebar-mini">
    <div class="wrapper">

      <!-- Main Header -->
      {% block header %}
      <header class="main-header">

        <!-- Logo -->
        <a href="{% url 'home' %}" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>O</b>SF</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>OSF</b>Admin</span>
        </a>
        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">

            <ul class="nav navbar-nav">
              {% if user.is_authenticated %}
              <!-- User Account Menu -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                  <span class="hidden-xs">
                      Logged in as {{ request.user.get_username }}
                      <span class="caret"></span>
                  </span>
                </a>
                <ul class="dropdown-menu user-menu">
                    {%  if perms.osf.change_osfuser %}
                  <li>
                    <a href="{% url 'auth:register' %}">
                      Admin-User Registration
                    </a>
                  </li>
                    {% endif %}
                  <li>
                    <a href="{% url 'auth:desk' %}">
                      Desk information
                    </a>
                  </li>
                </ul>
              </li>
              <li>
                <a href="{% url 'auth:logout' %}" class="btn btn-danger btn-flat">Sign out</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </nav>
        {% endblock %}
      </header>
      {% block sidebar %}
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">

        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar Menu -->
          <ul class="sidebar-menu">
            <li class="header">Menu</li>
            {% if perms.osf.view_node %}
                <li><a role="button" data-toggle="collapse" href="#collapseNodes">
                  <i class='fa fa-caret-down'></i> OSF Nodes
              </a></li>
            <li>
                <div class="collapse" id="collapseNodes">
                    <ul class="sidebar-menu sidebar-menu-inner">
                        <li><a href="{% url 'nodes:search' %}"><i class='fa fa-link'></i><span> OSF Nodes</span> </a></li>
                        <li><a href="{% url 'nodes:flagged-spam' %}"><i class="fa fa-exclamation-triangle"></i><span> Flagged Spam</span> </a></li>
                        <li><a href="{% url 'nodes:known-spam' %}"><i class="fa fa-cutlery"></i><span> Known Spam</span> </a></li>
                        <li><a href="{% url 'nodes:known-ham' %}"><i class="fa fa-star"></i><span> Known Ham</span> </a></li>
                    </ul>
                </div>
            </li>
            {% endif %}
            {% if perms.osf.view_preprintservice %}
            <li><a href="{% url 'preprints:search' %}"><i class='fa fa-link'></i><span>Preprints</span> </a></li>
            {% endif %}
          {% if perms.osf.view_osfuser %}
              <li><a role="button" data-toggle="collapse" href="#collapseUsers">
                  <i class='fa fa-caret-down'></i> OSF Users
              </a></li>
              <div class="collapse" id="collapseUsers">
                  <ul class="sidebar-menu sidebar-menu-inner">
                      <li><a href="{% url 'users:search' %}"><i class='fa fa-link'></i><span>OSF Users</span> </a></li>
                      <li><a href="{% url 'users:flagged-spam' %}"><i class="fa fa-exclamation-triangle"></i><span> Flagged Spam</span> </a></li>
                      <li><a href="{% url 'users:known-spam' %}"><i class="fa fa-cutlery"></i><span> Known Spam</span> </a></li>
                      <li><a href="{% url 'users:known-ham' %}"><i class="fa fa-star"></i><span> Known Ham</span> </a></li>
                  </ul>
              </div>
          {% endif %}
          {% if perms.osf.view_spam %}
            <li><a href="{% url 'spam:spam' %}"><i class='fa fa-link'></i> <span>OSF Spam</span></a></li>
          {% endif %}
          {% if perms.osf.view_registration %}
            <li><a href="{% url 'nodes:registrations' %}"><i class='fa fa-link'></i> <span>OSF Registrations</span></a></li>
          {% endif %}
          {% if perms.osf.view_institution %}
              <li><a role="button" data-toggle="collapse" href="#collapseInstitutions">
                  <i class='fa fa-caret-down'></i> OSF Institutions
              </a></li>
              <div class="collapse" id="collapseInstitutions">
                  <ul class="sidebar-menu sidebar-menu-inner">
                      <li><a href="{% url 'institutions:list' %}"><i class='fa fa-link'></i><span> List</span> </a></li>
                      {% if perms.osf.change_institution %}
                      <li><a href="{% url 'institutions:create' %}"><i class='fa fa-link'></i><span> Create</span> </a></li>
                      {% endif %}
                  </ul>
              </div>
          {% endif %}
          {% if perms.osf.view_preprintprovider %}
              <li><a role="button" data-toggle="collapse" href="#collapsePreprintProviders">
                  <i class='fa fa-caret-down'></i> Preprint Providers
              </a></li>
              <div class="collapse" id="collapsePreprintProviders">
                  <ul class="sidebar-menu sidebar-menu-inner">
                      <li><a href="{% url 'preprint_providers:list' %}"><i class='fa fa-link'></i><span> List</span> </a></li>
                      {% if perms.osf.change_preprintprovider %}
                      <li><a href="{% url 'preprint_providers:create' %}"><i class='fa fa-link'></i><span> Create</span> </a></li>
                      {% endif %}
                  </ul>
              </div>
          {% endif %}
          {% if perms.osf.view_conference %}
            <li><a href="{% url 'meetings:list' %}"><i class='fa fa-link'></i> <span>OSF Meetings</span></a></li>
          {% endif %}
          {% if perms.osf.view_prereg %}
            <li><a href="{% url 'pre_reg:prereg' %}"><i class='fa fa-link'></i> <span>OSF Prereg</span></a></li>
            {% endif %}
          {% if perms.osf.view_metrics %}
            <li><a href="{% url 'metrics:metrics' %}"><i class='fa fa-link'></i> <span>OSF Metrics</span></a></li>
          {% endif %}
          {% if perms.osf.view_subject%}
            <li><a href="{% url 'subjects:list' %}"><i class='fa fa-link'></i> <span>OSF Subjects</span></a></li>
          {% endif %}
          </ul><!-- /.sidebar-menu -->
        </section>
        <!-- /.sidebar -->
      </aside>
      {% endblock %}
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->

        <!-- Main content -->
        <section class="content">
          {% block content %}
          <h1>
           Welcome to the OSF Admin Home Page
          </h1>
          <!-- Your Page Content Here -->
          {% endblock %}
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

      <!-- Main Footer -->
      <footer class="main-footer">
        <!-- Default to the left -->
        <strong>Copyright &copy; 2015-2016 <a href="http://www.osf.io">osf.io</a>.</strong> All rights reserved.
      </footer>

    </div><!-- ./wrapper -->

    <!-- Included JS -->
    {% render_bundle 'vendor' %}
    {% render_bundle 'admin-base-page' %}

    {% block bottom_js %}

    {% endblock %}

  </body>
</html>

{% if 'admin.osf.io' in request.META.HTTP_HOST and not '-admin.osf.io' in request.META.HTTP_HOST %}
  <style>
    .navbar { background-color: #bc493c !important;}
    .logo { background-color: #a53e35 !important;}
  </style>
{% endif %}

admin/templates/base_analytics.html
{% extends 'base.html' %}
{% load static %}

{% block top_includes %}
    <script>
        if ('{{ keen_ready }}' == 'True') {
            var keenProjectId = '{{ keen_project_id }}';
            var keenReadKey = '{{ keen_read_key }}';
        }
    </script>

    {% block top_analytics %}
    {% endblock top_analytics %}

{% endblock top_includes %}

{% block title %}
    <title>OSF Sales Analytics</title>
{% endblock title %}


{% block content %}

    {% block topmenu %}
        <a href="{% url 'sales_analytics:dashboard' %}" class="btn btn-primary">
            Analytics Dashboard
        </a>
    {% endblock topmenu %}

    {% block title_analytics %}

    {% endblock title_analytics %}

    {% block content_analytics %}

    {% endblock content_analytics %}

{% endblock content %}

admin/templates/password_change_done.html
{% extends 'base.html' %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block content %}
    {{ title }}
{% endblock %}